import jsPDF from 'jspdf';
import 'jspdf-autotable';

interface CareerMatch {
  title: string;
  matchScore: number;
  reasoning: string;
  salaryRange: string;
  growthPotential: string;
}

interface PathwayStep {
  month: string;
  title: string;
  description: string;
  actions: string[];
  milestones: string[];
}

interface Analysis {
  topCareerMatches: CareerMatch[];
  sixMonthPathway: PathwayStep[];
  threeYearPathway: PathwayStep[];
  strengthsSummary: string[];
  developmentAreas: string[];
  confidenceScore: number;
  astrologyData?: any;
  palmistryData?: any;
  faceReadingData?: any;
}

const translations = {
  en: {
    title: 'Comprehensive Career & Life Blueprint',
    subtitle: 'Based on Ancient Wisdom & Modern Analysis',
    date: 'Report Generated',
    confidenceScore: 'Analysis Confidence Score',
    topCareers: 'Top Career Recommendations',
    match: 'Match',
    reasoning: 'Reasoning',
    salaryRange: 'Expected Salary Range',
    growthPotential: 'Growth Potential',
    strengths: 'Your Key Strengths',
    development: 'Areas for Development',
    sixMonthPlan: '6-Month Career Pathway',
    threeYearPlan: '3-Year Career Roadmap',
    actions: 'Action Steps',
    milestones: 'Success Milestones',
    footer: 'Generated by LifeOn66 - Your Cosmic Career Guide',
    basedOn: 'Based on Comprehensive Analysis of Astrology, Palmistry, and Face Reading',
    year: 'Year',
    month: 'Month',
    executiveSummary: 'Executive Summary',
    astrologySection: 'Vedic Astrology Analysis',
    palmistrySection: 'Palmistry Insights',
    faceReadingSection: 'Face Reading Analysis',
    careerHouse: 'Career House (10th House)',
    wealthHouse: 'Wealth House (2nd House)',
    gainsHouse: 'Gains & Networks (11th House)',
    planetaryPositions: 'Planetary Positions',
    housePlacements: 'House Placements',
    dashaSystem: 'Dasha Periods',
    yogaAnalysis: 'Yoga Formations',
    recommendedActions: 'Recommended Actions',
    keyInsights: 'Key Insights',
    planet: 'Planet',
    sign: 'Sign',
    house: 'House',
    degree: 'Degree',
    period: 'Period',
    effect: 'Effect',
    tableOfContents: 'Table of Contents',
    page: 'Page',
    introduction: 'Introduction',
    aboutReport: 'About This Report',
    howToUse: 'How to Use This Report',
    detailedAnalysis: 'Detailed Analysis',
    actionPlan: 'Action Plan',
    conclusion: 'Conclusion',
    disclaimer: 'Disclaimer',
    disclaimerText: 'This report is based on ancient wisdom traditions combined with modern analytical techniques. Results should be used as guidance for self-reflection and personal development. Individual results may vary.',
    integratedGuidance: 'Integrated Career Guidance'
  },
  hi: {
    title: 'व्यापक करियर और जीवन ब्लूप्रिंट',
    subtitle: 'प्राचीन ज्ञान और आधुनिक विश्लेषण पर आधारित',
    date: 'रिपोर्ट तैयार की गई',
    confidenceScore: 'विश्लेषण विश्वास स्कोर',
    topCareers: 'शीर्ष करियर सिफारिशें',
    match: 'मैच',
    reasoning: 'तर्क',
    salaryRange: 'अपेक्षित वेतन सीमा',
    growthPotential: 'विकास क्षमता',
    strengths: 'आपकी मुख्य शक्तियां',
    development: 'विकास के क्षेत्र',
    sixMonthPlan: '6 महीने का करियर मार्ग',
    threeYearPlan: '3 साल का करियर रोडमैप',
    actions: 'कार्य चरण',
    milestones: 'सफलता के मील के पत्थर',
    footer: 'LifeOn66 द्वारा उत्पन्न - आपका ब्रह्मांडीय करियर गाइड',
    basedOn: 'ज्योतिष, हस्तरेखा विज्ञान और चेहरा पढ़ने के व्यापक विश्लेषण पर आधारित',
    year: 'वर्ष',
    month: 'महीना',
    executiveSummary: 'कार्यकारी सारांश',
    astrologySection: 'वैदिक ज्योतिष विश्लेषण',
    palmistrySection: 'हस्तरेखा विज्ञान अंतर्दृष्टि',
    faceReadingSection: 'चेहरा पढ़ना विश्लेषण',
    careerHouse: 'करियर भाव (10वां भाव)',
    wealthHouse: 'धन भाव (2रा भाव)',
    gainsHouse: 'लाभ और नेटवर्क (11वां भाव)',
    planetaryPositions: 'ग्रह स्थिति',
    housePlacements: 'भाव स्थापन',
    dashaSystem: 'दशा काल',
    yogaAnalysis: 'योग विश्लेषण',
    recommendedActions: 'अनुशंसित कार्रवाई',
    keyInsights: 'मुख्य अंतर्दृष्टि',
    planet: 'ग्रह',
    sign: 'राशि',
    house: 'भाव',
    degree: 'डिग्री',
    period: 'अवधि',
    effect: 'प्रभाव',
    tableOfContents: 'विषयसूची',
    page: 'पृष्ठ',
    introduction: 'परिचय',
    aboutReport: 'इस रिपोर्ट के बारे में',
    howToUse: 'इस रिपोर्ट का उपयोग कैसे करें',
    detailedAnalysis: 'विस्तृत विश्लेषण',
    actionPlan: 'कार्य योजना',
    conclusion: 'निष्कर्ष',
    disclaimer: 'अस्वीकरण',
    disclaimerText: 'यह रिपोर्ट प्राचीन ज्ञान परंपराओं और आधुनिक विश्लेषणात्मक तकनीकों पर आधारित है। परिणामों का उपयोग आत्म-चिंतन और व्यक्तिगत विकास के लिए मार्गदर्शन के रूप में किया जाना चाहिए। व्यक्तिगत परिणाम भिन्न हो सकते हैं।',
    integratedGuidance: 'एकीकृत करियर मार्गदर्शन'
  }
};

export const generatePDFReport = (analysis: Analysis, language: 'en' | 'hi' = 'en', userName?: string) => {
  const t = translations[language];
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;
  let currentPage = 1;

  const addPageNumber = () => {
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(`${t.page} ${currentPage}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    doc.text(t.footer, pageWidth / 2, pageHeight - 5, { align: 'center' });
  };

  const addNewPage = () => {
    addPageNumber();
    doc.addPage();
    currentPage++;
    yPosition = 20;
  };

  const checkPageBreak = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - 20) {
      addNewPage();
    }
  };

  const addSectionHeader = (title: string, color: number[] = [75, 0, 130]) => {
    checkPageBreak(25);
    doc.setFillColor(color[0], color[1], color[2]);
    doc.rect(0, yPosition - 5, pageWidth, 15, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(title, pageWidth / 2, yPosition + 5, { align: 'center' });
    yPosition += 20;
    doc.setTextColor(0, 0, 0);
  };

  doc.setFillColor(25, 25, 112);
  doc.rect(0, 0, pageWidth, 80, 'F');

  doc.setTextColor(255, 215, 0);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text(t.title, pageWidth / 2, 35, { align: 'center' });

  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'normal');
  doc.text(t.subtitle, pageWidth / 2, 50, { align: 'center' });

  doc.setFontSize(10);
  doc.text(t.basedOn, pageWidth / 2, 62, { align: 'center' });

  yPosition = 90;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`${t.date}: ${new Date().toLocaleDateString(language === 'hi' ? 'hi-IN' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })}`, 20, yPosition);

  if (userName) {
    yPosition += 8;
    doc.setFont('helvetica', 'bold');
    doc.text(language === 'hi' ? `नाम: ${userName}` : `Name: ${userName}`, 20, yPosition);
  }

  yPosition += 20;
  doc.setFillColor(240, 248, 255);
  doc.roundedRect(15, yPosition, pageWidth - 30, 25, 5, 5, 'F');
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(75, 0, 130);
  doc.text(`${t.confidenceScore}: ${analysis.confidenceScore}%`, pageWidth / 2, yPosition + 16, { align: 'center' });
  yPosition += 35;

  addNewPage();

  addSectionHeader(t.tableOfContents, [47, 79, 79]);

  const tocItems = [
    { title: t.executiveSummary, page: 3 },
    { title: t.topCareers, page: 4 },
    { title: t.astrologySection, page: 7 },
    { title: t.palmistrySection, page: 12 },
    { title: t.faceReadingSection, page: 14 },
    { title: t.sixMonthPlan, page: 16 },
    { title: t.threeYearPlan, page: 18 },
    { title: t.conclusion, page: 21 }
  ];

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  tocItems.forEach(item => {
    checkPageBreak(10);
    doc.setTextColor(0, 0, 0);
    doc.text(item.title, 25, yPosition);
    doc.line(25, yPosition + 1, pageWidth - 40, yPosition + 1);
    doc.text(`${item.page}`, pageWidth - 30, yPosition);
    yPosition += 10;
  });

  addNewPage();
  addSectionHeader(t.executiveSummary, [0, 100, 0]);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  const summaryText = language === 'hi'
    ? `यह व्यापक रिपोर्ट आपके करियर पथ और जीवन क्षमता का गहन विश्लेषण प्रदान करती है। हमने वैदिक ज्योतिष, हस्तरेखा विज्ञान, और चेहरा पढ़ने के प्राचीन विज्ञान को आधुनिक विश्लेषणात्मक तकनीकों के साथ जोड़ा है। यह रिपोर्ट आपकी अद्वितीय शक्तियों, प्रतिभाओं, और अवसरों की पहचान करती है। ${analysis.confidenceScore}% विश्वास स्कोर इस विश्लेषण की सटीकता और विश्वसनीयता को दर्शाता है।`
    : `This comprehensive report provides an in-depth analysis of your career path and life potential. We have combined the ancient sciences of Vedic Astrology, Palmistry, and Face Reading with modern analytical techniques. This report identifies your unique strengths, talents, and opportunities. The ${analysis.confidenceScore}% confidence score reflects the accuracy and reliability of this analysis.`;

  const summaryLines = doc.splitTextToSize(summaryText, pageWidth - 40);
  summaryLines.forEach((line: string) => {
    checkPageBreak(8);
    doc.text(line, 20, yPosition);
    yPosition += 7;
  });

  yPosition += 15;
  checkPageBreak(15);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text(t.keyInsights + ':', 20, yPosition);
  yPosition += 10;

  const insights = analysis.strengthsSummary.slice(0, 5);
  insights.forEach((insight) => {
    checkPageBreak(12);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 100, 0);
    doc.setFillColor(220, 255, 220);
    doc.circle(23, yPosition - 2, 2, 'F');
    doc.setTextColor(0, 0, 0);
    const insightLines = doc.splitTextToSize(insight, pageWidth - 50);
    doc.text(insightLines, 30, yPosition);
    yPosition += insightLines.length * 6 + 4;
  });

  addNewPage();
  addSectionHeader(t.topCareers, [75, 0, 130]);

  analysis.topCareerMatches.forEach((career, careerIndex) => {
    checkPageBreak(70);

    doc.setFillColor(250, 245, 255);
    doc.roundedRect(15, yPosition, pageWidth - 30, 60, 5, 5, 'F');

    doc.setDrawColor(138, 43, 226);
    doc.setLineWidth(0.5);
    doc.roundedRect(15, yPosition, pageWidth - 30, 60, 5, 5, 'S');

    doc.setFontSize(15);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(75, 0, 130);
    doc.text(`${careerIndex + 1}. ${career.title}`, 20, yPosition + 10);

    doc.setFontSize(13);
    doc.setTextColor(0, 150, 0);
    doc.text(`${t.match}: ${career.matchScore}%`, pageWidth - 50, yPosition + 10);

    doc.setFillColor(0, 150, 0);
    const barWidth = (career.matchScore / 100) * 30;
    doc.rect(pageWidth - 50, yPosition + 13, barWidth, 3, 'F');

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);

    const reasoningLines = doc.splitTextToSize(`${t.reasoning}: ${career.reasoning}`, pageWidth - 50);
    doc.text(reasoningLines, 20, yPosition + 22);

    yPosition += 22 + (reasoningLines.length * 5);

    doc.setFontSize(9);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'bold');
    doc.text(`${t.salaryRange}:`, 20, yPosition + 8);
    doc.setFont('helvetica', 'normal');
    doc.text(career.salaryRange, 60, yPosition + 8);

    doc.setFont('helvetica', 'bold');
    doc.text(`${t.growthPotential}:`, 20, yPosition + 15);
    doc.setFont('helvetica', 'normal');
    const growthLines = doc.splitTextToSize(career.growthPotential, pageWidth - 70);
    doc.text(growthLines, 60, yPosition + 15);

    yPosition += 35;
  });

  addNewPage();
  addSectionHeader(t.strengths, [34, 139, 34]);

  analysis.strengthsSummary.forEach((strength) => {
    checkPageBreak(15);

    doc.setFillColor(240, 255, 240);
    doc.roundedRect(15, yPosition - 3, pageWidth - 30, 10, 2, 2, 'F');

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 128, 0);
    doc.text(`✓`, 20, yPosition + 4);

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    const lines = doc.splitTextToSize(strength, pageWidth - 45);
    doc.text(lines, 28, yPosition + 4);
    yPosition += Math.max(10, lines.length * 6 + 2);
  });

  yPosition += 15;
  checkPageBreak(20);
  addSectionHeader(t.development, [255, 140, 0]);

  analysis.developmentAreas.forEach((area) => {
    checkPageBreak(15);

    doc.setFillColor(255, 250, 240);
    doc.roundedRect(15, yPosition - 3, pageWidth - 30, 10, 2, 2, 'F');

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 140, 0);
    doc.text(`►`, 20, yPosition + 4);

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    const lines = doc.splitTextToSize(area, pageWidth - 45);
    doc.text(lines, 28, yPosition + 4);
    yPosition += Math.max(10, lines.length * 6 + 2);
  });

  if (analysis.astrologyData) {
    addNewPage();
    addSectionHeader(t.astrologySection, [128, 0, 128]);

    if (analysis.astrologyData.planets && analysis.astrologyData.planets.length > 0) {
      checkPageBreak(15);
      doc.setFontSize(13);
      doc.setFont('helvetica', 'bold');
      doc.text(t.planetaryPositions, 20, yPosition);
      yPosition += 10;

      const planetaryData = analysis.astrologyData.planets.map((p: any) => [
        p.name || '',
        p.sign || '',
        `${t.house} ${p.house || ''}`,
        p.degree ? `${parseFloat(p.degree).toFixed(1)}°` : ''
      ]);

      (doc as any).autoTable({
        startY: yPosition,
        head: [[t.planet, t.sign, t.house, t.degree]],
        body: planetaryData,
        theme: 'grid',
        headStyles: { fillColor: [128, 0, 128], textColor: [255, 255, 255], fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [250, 240, 255] },
        margin: { left: 20, right: 20 },
        styles: { fontSize: 9, cellPadding: 3 }
      });

      yPosition = (doc as any).lastAutoTable.finalY + 15;
    }

    if (analysis.astrologyData.house10Details) {
      checkPageBreak(40);
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(128, 0, 128);
      doc.text(t.careerHouse, 20, yPosition);
      yPosition += 8;

      doc.setFillColor(250, 240, 255);
      doc.roundedRect(15, yPosition, pageWidth - 30, 35, 3, 3, 'F');

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(0, 0, 0);
      const house10Lines = doc.splitTextToSize(analysis.astrologyData.house10Details.analysis || '', pageWidth - 40);
      doc.text(house10Lines, 20, yPosition + 6);
      yPosition += 45;
    }

    if (analysis.astrologyData.house2Details) {
      checkPageBreak(40);
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(128, 0, 128);
      doc.text(t.wealthHouse, 20, yPosition);
      yPosition += 8;

      doc.setFillColor(250, 240, 255);
      doc.roundedRect(15, yPosition, pageWidth - 30, 35, 3, 3, 'F');

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(0, 0, 0);
      const house2Lines = doc.splitTextToSize(analysis.astrologyData.house2Details.analysis || '', pageWidth - 40);
      doc.text(house2Lines, 20, yPosition + 6);
      yPosition += 45;
    }

    if (analysis.astrologyData.house11Details) {
      checkPageBreak(40);
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(128, 0, 128);
      doc.text(t.gainsHouse, 20, yPosition);
      yPosition += 8;

      doc.setFillColor(250, 240, 255);
      doc.roundedRect(15, yPosition, pageWidth - 30, 35, 3, 3, 'F');

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(0, 0, 0);
      const house11Lines = doc.splitTextToSize(analysis.astrologyData.house11Details.analysis || '', pageWidth - 40);
      doc.text(house11Lines, 20, yPosition + 6);
      yPosition += 45;
    }

    if (analysis.astrologyData.integratedCareerGuidance) {
      addNewPage();
      doc.setFontSize(13);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(128, 0, 128);
      doc.text(t.integratedGuidance, 20, yPosition);
      yPosition += 10;

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(0, 0, 0);
      const guidanceLines = doc.splitTextToSize(analysis.astrologyData.integratedCareerGuidance, pageWidth - 40);
      guidanceLines.forEach((line: string) => {
        checkPageBreak(6);
        doc.text(line, 20, yPosition);
        yPosition += 5;
      });
    }

    if (analysis.astrologyData.dashas && analysis.astrologyData.dashas.length > 0) {
      addNewPage();
      doc.setFontSize(13);
      doc.setFont('helvetica', 'bold');
      doc.text(t.dashaSystem, 20, yPosition);
      yPosition += 10;

      const dashaData = analysis.astrologyData.dashas.map((d: any) => [
        d.planet || '',
        d.period || '',
        d.effect || ''
      ]);

      (doc as any).autoTable({
        startY: yPosition,
        head: [[t.planet, t.period, t.effect]],
        body: dashaData,
        theme: 'striped',
        headStyles: { fillColor: [128, 0, 128], textColor: [255, 255, 255] },
        margin: { left: 20, right: 20 },
        styles: { fontSize: 9 }
      });

      yPosition = (doc as any).lastAutoTable.finalY + 15;
    }

    if (analysis.astrologyData.yogas && analysis.astrologyData.yogas.length > 0) {
      checkPageBreak(15);
      doc.setFontSize(13);
      doc.setFont('helvetica', 'bold');
      doc.text(t.yogaAnalysis, 20, yPosition);
      yPosition += 10;

      analysis.astrologyData.yogas.forEach((yoga: string) => {
        checkPageBreak(10);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(75, 0, 130);
        doc.text('◆', 20, yPosition);
        doc.setTextColor(0, 0, 0);
        const yogaLines = doc.splitTextToSize(yoga, pageWidth - 40);
        doc.text(yogaLines, 28, yPosition);
        yPosition += yogaLines.length * 6 + 3;
      });
    }
  }

  if (analysis.palmistryData) {
    addNewPage();
    addSectionHeader(t.palmistrySection, [184, 134, 11]);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    const palmText = language === 'hi'
      ? 'हस्तरेखा विज्ञान प्राचीन विज्ञान है जो हाथ की रेखाओं और आकृतियों का अध्ययन करता है। आपके हाथ आपके व्यक्तित्व, प्रतिभा और भविष्य की संभावनाओं के बारे में महत्वपूर्ण जानकारी प्रकट करते हैं।'
      : 'Palmistry is the ancient science of studying the lines and shapes of the hand. Your hands reveal important information about your personality, talents, and future possibilities.';

    const palmLines = doc.splitTextToSize(palmText, pageWidth - 40);
    palmLines.forEach((line: string) => {
      checkPageBreak(8);
      doc.text(line, 20, yPosition);
      yPosition += 7;
    });
    yPosition += 10;
  }

  if (analysis.faceReadingData) {
    addNewPage();
    addSectionHeader(t.faceReadingSection, [220, 20, 60]);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    const faceText = language === 'hi'
      ? 'चेहरा पढ़ना (सामुद्रिक शास्त्र) एक प्राचीन विज्ञान है जो चेहरे की विशेषताओं का विश्लेषण करता है। आपके चेहरे की विशेषताएं आपके स्वभाव, क्षमताओं और जीवन पथ के बारे में महत्वपूर्ण संकेत देती हैं।'
      : 'Face Reading (Samudrik Shastra) is an ancient science that analyzes facial features. Your facial features provide important clues about your nature, abilities, and life path.';

    const faceLines = doc.splitTextToSize(faceText, pageWidth - 40);
    faceLines.forEach((line: string) => {
      checkPageBreak(8);
      doc.text(line, 20, yPosition);
      yPosition += 7;
    });
    yPosition += 10;
  }

  addNewPage();
  addSectionHeader(t.sixMonthPlan, [0, 100, 200]);

  analysis.sixMonthPathway.forEach((step) => {
    checkPageBreak(85);

    doc.setFillColor(240, 248, 255);
    doc.roundedRect(15, yPosition, pageWidth - 30, 80, 5, 5, 'F');

    doc.setDrawColor(0, 100, 200);
    doc.setLineWidth(1);
    doc.roundedRect(15, yPosition, pageWidth - 30, 80, 5, 5, 'S');

    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 100, 200);
    doc.text(`${step.month}: ${step.title}`, 20, yPosition + 10);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);
    const descLines = doc.splitTextToSize(step.description, pageWidth - 50);
    doc.text(descLines, 20, yPosition + 20);

    let actionY = yPosition + 20 + (descLines.length * 5) + 5;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text(t.actions + ':', 20, actionY);

    doc.setFont('helvetica', 'normal');
    actionY += 5;
    step.actions.slice(0, 3).forEach(action => {
      const actionLines = doc.splitTextToSize(`• ${action}`, pageWidth - 50);
      doc.text(actionLines, 22, actionY);
      actionY += actionLines.length * 4.5;
    });

    actionY += 3;
    doc.setFont('helvetica', 'bold');
    doc.text(t.milestones + ':', 20, actionY);
    doc.setFont('helvetica', 'normal');
    actionY += 5;
    step.milestones.slice(0, 2).forEach(milestone => {
      const milestoneLines = doc.splitTextToSize(`✓ ${milestone}`, pageWidth - 50);
      doc.text(milestoneLines, 22, actionY);
      actionY += milestoneLines.length * 4.5;
    });

    yPosition += 90;
  });

  addNewPage();
  addSectionHeader(t.threeYearPlan, [128, 0, 128]);

  analysis.threeYearPathway.forEach((step, index) => {
    checkPageBreak(85);

    doc.setFillColor(250, 240, 255);
    doc.roundedRect(15, yPosition, pageWidth - 30, 80, 5, 5, 'F');

    doc.setDrawColor(128, 0, 128);
    doc.setLineWidth(1);
    doc.roundedRect(15, yPosition, pageWidth - 30, 80, 5, 5, 'S');

    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(128, 0, 128);
    doc.text(`${t.year} ${index + 1}: ${step.title}`, 20, yPosition + 10);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);
    const descLines = doc.splitTextToSize(step.description, pageWidth - 50);
    doc.text(descLines, 20, yPosition + 20);

    let actionY = yPosition + 20 + (descLines.length * 5) + 5;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text(t.actions + ':', 20, actionY);

    doc.setFont('helvetica', 'normal');
    actionY += 5;
    step.actions.slice(0, 3).forEach(action => {
      const actionLines = doc.splitTextToSize(`• ${action}`, pageWidth - 50);
      doc.text(actionLines, 22, actionY);
      actionY += actionLines.length * 4.5;
    });

    actionY += 3;
    doc.setFont('helvetica', 'bold');
    doc.text(t.milestones + ':', 20, actionY);
    doc.setFont('helvetica', 'normal');
    actionY += 5;
    step.milestones.slice(0, 2).forEach(milestone => {
      const milestoneLines = doc.splitTextToSize(`✓ ${milestone}`, pageWidth - 50);
      doc.text(milestoneLines, 22, actionY);
      actionY += milestoneLines.length * 4.5;
    });

    yPosition += 90;
  });

  addNewPage();
  addSectionHeader(t.conclusion, [47, 79, 79]);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  const conclusionText = language === 'hi'
    ? `यह रिपोर्ट आपके करियर और जीवन की यात्रा के लिए एक व्यापक मार्गदर्शिका है। प्राचीन ज्ञान और आधुनिक विश्लेषण के संयोजन से, हमने आपकी अद्वितीय क्षमताओं और अवसरों की पहचान की है। याद रखें कि यह मार्गदर्शन है, न कि निर्धारित भाग्य। आपकी मेहनत, समर्पण और सही निर्णय आपकी सफलता के मुख्य कारक होंगे। इस रिपोर्ट का उपयोग अपनी यात्रा को नेविगेट करने और अपने लक्ष्यों को प्राप्त करने के लिए करें। आपकी सफलता की शुभकामनाएं!`
    : `This report is a comprehensive guide for your career and life journey. Through the combination of ancient wisdom and modern analysis, we have identified your unique abilities and opportunities. Remember that this is guidance, not predetermined fate. Your hard work, dedication, and right decisions will be the main factors of your success. Use this report to navigate your journey and achieve your goals. Best wishes for your success!`;

  const conclusionLines = doc.splitTextToSize(conclusionText, pageWidth - 40);
  conclusionLines.forEach((line: string) => {
    checkPageBreak(8);
    doc.text(line, 20, yPosition);
    yPosition += 7;
  });

  yPosition += 15;
  checkPageBreak(25);
  doc.setFillColor(255, 255, 220);
  doc.roundedRect(15, yPosition, pageWidth - 30, 30, 3, 3, 'F');

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(150, 0, 0);
  doc.text(t.disclaimer, 20, yPosition + 8);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  const disclaimerLines = doc.splitTextToSize(t.disclaimerText, pageWidth - 40);
  doc.text(disclaimerLines, 20, yPosition + 15);

  addPageNumber();

  const fileName = `Career_Blueprint_${language.toUpperCase()}_${new Date().getTime()}.pdf`;
  doc.save(fileName);
};
