import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

interface CareerMatch {
  title: string;
  matchScore: number;
  reasoning: string;
  salaryRange: string;
  growthPotential: string;
}

interface PathwayStep {
  month: string;
  title: string;
  description: string;
  actions: string[];
  milestones: string[];
}

interface Analysis {
  topCareerMatches: CareerMatch[];
  sixMonthPathway: PathwayStep[];
  threeYearPathway: PathwayStep[];
  strengthsSummary: string[];
  developmentAreas: string[];
  confidenceScore: number;
  astrologyData?: any;
  palmistryData?: any;
  faceReadingData?: any;
}

const translations = {
  en: {
    title: 'Comprehensive Career & Life Blueprint',
    subtitle: 'Based on Ancient Wisdom & Modern Analysis',
    date: 'Report Generated',
    confidenceScore: 'Analysis Confidence Score',
    topCareers: 'Top Career Recommendations',
    match: 'Match',
    reasoning: 'Reasoning',
    salaryRange: 'Expected Salary Range',
    growthPotential: 'Growth Potential',
    strengths: 'Your Key Strengths',
    development: 'Areas for Development',
    sixMonthPlan: '6-Month Career Pathway',
    threeYearPlan: '3-Year Career Roadmap',
    actions: 'Action Steps',
    milestones: 'Success Milestones',
    footer: 'Generated by LifeOn66 - Your Cosmic Career Guide',
    basedOn: 'Based on Comprehensive Analysis of Astrology, Palmistry, and Face Reading',
    year: 'Year',
    month: 'Month',
    executiveSummary: 'Executive Summary',
    astrologySection: 'Vedic Astrology Analysis',
    palmistrySection: 'Palmistry Insights',
    faceReadingSection: 'Face Reading Analysis',
    careerHouse: 'Career House (10th House)',
    wealthHouse: 'Wealth House (2nd House)',
    gainsHouse: 'Gains & Networks (11th House)',
    planetaryPositions: 'Planetary Positions',
    housePlacements: 'House Placements',
    dashaSystem: 'Dasha Periods',
    yogaAnalysis: 'Yoga Formations',
    recommendedActions: 'Recommended Actions',
    keyInsights: 'Key Insights',
    planet: 'Planet',
    sign: 'Sign',
    house: 'House',
    degree: 'Degree',
    period: 'Period',
    effect: 'Effect',
    tableOfContents: 'Table of Contents',
    page: 'Page',
    introduction: 'Introduction',
    aboutReport: 'About This Report',
    howToUse: 'How to Use This Report',
    detailedAnalysis: 'Detailed Analysis',
    actionPlan: 'Action Plan',
    conclusion: 'Conclusion',
    disclaimer: 'Disclaimer',
    disclaimerText: 'This report is based on ancient wisdom traditions combined with modern analytical techniques. Results should be used as guidance for self-reflection and personal development. Individual results may vary.',
    integratedGuidance: 'Integrated Career Guidance'
  },
  hi: {
    title: 'व्यापक करियर और जीवन ब्लूप्रिंट',
    subtitle: 'प्राचीन ज्ञान और आधुनिक विश्लेषण पर आधारित',
    date: 'रिपोर्ट तैयार की गई',
    confidenceScore: 'विश्लेषण विश्वास स्कोर',
    topCareers: 'शीर्ष करियर सिफारिशें',
    match: 'मैच',
    reasoning: 'तर्क',
    salaryRange: 'अपेक्षित वेतन सीमा',
    growthPotential: 'विकास क्षमता',
    strengths: 'आपकी मुख्य शक्तियां',
    development: 'विकास के क्षेत्र',
    sixMonthPlan: '6 महीने का करियर मार्ग',
    threeYearPlan: '3 साल का करियर रोडमैप',
    actions: 'कार्य चरण',
    milestones: 'सफलता के मील के पत्थर',
    footer: 'LifeOn66 द्वारा उत्पन्न - आपका ब्रह्मांडीय करियर गाइड',
    basedOn: 'ज्योतिष, हस्तरेखा विज्ञान और चेहरा पढ़ने के व्यापक विश्लेषण पर आधारित',
    year: 'वर्ष',
    month: 'महीना',
    executiveSummary: 'कार्यकारी सारांश',
    astrologySection: 'वैदिक ज्योतिष विश्लेषण',
    palmistrySection: 'हस्तरेखा विज्ञान अंतर्दृष्टि',
    faceReadingSection: 'चेहरा पढ़ना विश्लेषण',
    careerHouse: 'करियर भाव (10वां भाव)',
    wealthHouse: 'धन भाव (2रा भाव)',
    gainsHouse: 'लाभ और नेटवर्क (11वां भाव)',
    planetaryPositions: 'ग्रह स्थिति',
    housePlacements: 'भाव स्थापन',
    dashaSystem: 'दशा काल',
    yogaAnalysis: 'योग विश्लेषण',
    recommendedActions: 'अनुशंसित कार्रवाई',
    keyInsights: 'मुख्य अंतर्दृष्टि',
    planet: 'ग्रह',
    sign: 'राशि',
    house: 'भाव',
    degree: 'डिग्री',
    period: 'अवधि',
    effect: 'प्रभाव',
    tableOfContents: 'विषयसूची',
    page: 'पृष्ठ',
    introduction: 'परिचय',
    aboutReport: 'इस रिपोर्ट के बारे में',
    howToUse: 'इस रिपोर्ट का उपयोग कैसे करें',
    detailedAnalysis: 'विस्तृत विश्लेषण',
    actionPlan: 'कार्य योजना',
    conclusion: 'निष्कर्ष',
    disclaimer: 'अस्वीकरण',
    disclaimerText: 'यह रिपोर्ट प्राचीन ज्ञान परंपराओं और आधुनिक विश्लेषणात्मक तकनीकों पर आधारित है। परिणामों का उपयोग आत्म-चिंतन और व्यक्तिगत विकास के लिए मार्गदर्शन के रूप में किया जाना चाहिए। व्यक्तिगत परिणाम भिन्न हो सकते हैं।',
    integratedGuidance: 'एकीकृत करियर मार्गदर्शन'
  }
};

function createHTMLContent(analysis: Analysis, language: 'en' | 'hi', userName?: string): string {
  const t = translations[language];
  const fontFamily = language === 'hi' ? "'Noto Sans Devanagari', sans-serif" : "'Arial', sans-serif";

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Devanagari:wght@400;600;700&display=swap" rel="stylesheet">
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
        body {
          font-family: ${fontFamily};
          line-height: 1.6;
          color: #333;
          background: white;
          padding: 40px;
          width: 210mm;
        }
        .cover {
          background: linear-gradient(135deg, #1e3a8a 0%, #4b0082 100%);
          color: white;
          padding: 60px 40px;
          text-align: center;
          margin: -40px -40px 40px -40px;
          min-height: 250px;
          display: flex;
          flex-direction: column;
          justify-content: center;
        }
        .cover h1 {
          font-size: 36px;
          font-weight: 700;
          margin-bottom: 20px;
          color: #ffd700;
        }
        .cover h2 {
          font-size: 20px;
          font-weight: 400;
          margin-bottom: 15px;
        }
        .cover p {
          font-size: 14px;
          opacity: 0.9;
        }
        .section {
          margin: 30px 0;
          page-break-inside: avoid;
        }
        .section-header {
          background: #4b0082;
          color: white;
          padding: 15px 20px;
          font-size: 22px;
          font-weight: 700;
          margin: 30px -40px 20px -40px;
        }
        .confidence-box {
          background: #f0f8ff;
          border: 3px solid #4b0082;
          border-radius: 10px;
          padding: 25px;
          text-align: center;
          margin: 20px 0;
        }
        .confidence-box h3 {
          font-size: 24px;
          color: #4b0082;
          font-weight: 700;
        }
        .career-card {
          background: #faf5ff;
          border: 2px solid #8a2be2;
          border-radius: 10px;
          padding: 20px;
          margin: 20px 0;
          page-break-inside: avoid;
        }
        .career-card h3 {
          color: #4b0082;
          font-size: 20px;
          margin-bottom: 10px;
          font-weight: 700;
        }
        .match-score {
          color: #009600;
          font-size: 18px;
          font-weight: 700;
          margin: 10px 0;
        }
        .match-bar {
          background: #e0e0e0;
          height: 10px;
          border-radius: 5px;
          overflow: hidden;
          margin: 10px 0;
        }
        .match-bar-fill {
          background: #009600;
          height: 100%;
          transition: width 0.3s;
        }
        .list-item {
          background: #f0fff0;
          border-left: 4px solid #228b22;
          padding: 12px 15px;
          margin: 10px 0;
          border-radius: 4px;
        }
        .dev-item {
          background: #fff5e6;
          border-left: 4px solid #ff8c00;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin: 20px 0;
        }
        th, td {
          border: 1px solid #ddd;
          padding: 12px;
          text-align: left;
        }
        th {
          background: #4b0082;
          color: white;
          font-weight: 700;
        }
        tr:nth-child(even) {
          background: #faf0ff;
        }
        .pathway-box {
          background: #f0f8ff;
          border: 2px solid #0064c8;
          border-radius: 10px;
          padding: 20px;
          margin: 20px 0;
          page-break-inside: avoid;
        }
        .pathway-box h3 {
          color: #0064c8;
          font-size: 18px;
          margin-bottom: 10px;
          font-weight: 700;
        }
        ul {
          margin: 10px 0;
          padding-left: 20px;
        }
        li {
          margin: 5px 0;
        }
        .footer {
          text-align: center;
          color: #666;
          font-size: 12px;
          margin-top: 40px;
          padding-top: 20px;
          border-top: 2px solid #ddd;
        }
        .disclaimer-box {
          background: #fffacd;
          border: 2px solid #ffa500;
          border-radius: 8px;
          padding: 20px;
          margin: 30px 0;
        }
        .disclaimer-box h4 {
          color: #960000;
          margin-bottom: 10px;
          font-weight: 700;
        }
        @media print {
          body {
            print-color-adjust: exact;
            -webkit-print-color-adjust: exact;
          }
          .section {
            page-break-after: auto;
          }
        }
      </style>
    </head>
    <body>
      <!-- Cover Page -->
      <div class="cover">
        <h1>${t.title}</h1>
        <h2>${t.subtitle}</h2>
        <p>${t.basedOn}</p>
        <p style="margin-top: 20px;">${t.date}: ${new Date().toLocaleDateString(language === 'hi' ? 'hi-IN' : 'en-US', {
          year: 'numeric',
          month: 'long',
          day: 'numeric'
        })}</p>
        ${userName ? `<p style="margin-top: 10px; font-weight: 700; font-size: 16px;">${language === 'hi' ? 'नाम' : 'Name'}: ${userName}</p>` : ''}
      </div>

      <!-- Confidence Score -->
      <div class="confidence-box">
        <h3>${t.confidenceScore}: ${analysis.confidenceScore}%</h3>
      </div>

      <!-- Executive Summary -->
      <div class="section-header">${t.executiveSummary}</div>
      <div class="section">
        <p>${language === 'hi'
          ? `यह व्यापक रिपोर्ट आपके करियर पथ और जीवन क्षमता का गहन विश्लेषण प्रदान करती है। हमने वैदिक ज्योतिष, हस्तरेखा विज्ञान, और चेहरा पढ़ने के प्राचीन विज्ञान को आधुनिक विश्लेषणात्मक तकनीकों के साथ जोड़ा है।`
          : `This comprehensive report provides an in-depth analysis of your career path and life potential. We have combined the ancient sciences of Vedic Astrology, Palmistry, and Face Reading with modern analytical techniques.`
        }</p>

        <h3 style="margin: 20px 0 10px 0; font-weight: 700;">${t.keyInsights}:</h3>
        ${analysis.strengthsSummary.slice(0, 5).map(insight => `
          <div class="list-item">• ${insight}</div>
        `).join('')}
      </div>

      <!-- Career Recommendations -->
      <div class="section-header">${t.topCareers}</div>
      ${analysis.topCareerMatches.map((career, index) => `
        <div class="career-card">
          <h3>${index + 1}. ${career.title}</h3>
          <div class="match-score">${t.match}: ${career.matchScore}%</div>
          <div class="match-bar">
            <div class="match-bar-fill" style="width: ${career.matchScore}%"></div>
          </div>
          <p style="margin: 10px 0;"><strong>${t.reasoning}:</strong> ${career.reasoning}</p>
          <p><strong>${t.salaryRange}:</strong> ${career.salaryRange}</p>
          <p><strong>${t.growthPotential}:</strong> ${career.growthPotential}</p>
        </div>
      `).join('')}

      <!-- Strengths -->
      <div class="section-header">${t.strengths}</div>
      ${analysis.strengthsSummary.map(strength => `
        <div class="list-item">✓ ${strength}</div>
      `).join('')}

      <!-- Development Areas -->
      <div class="section-header">${t.development}</div>
      ${analysis.developmentAreas.map(area => `
        <div class="list-item dev-item">► ${area}</div>
      `).join('')}

      ${analysis.astrologyData ? `
        <!-- Astrology Analysis -->
        <div class="section-header">${t.astrologySection}</div>

        ${analysis.astrologyData.planets && analysis.astrologyData.planets.length > 0 ? `
          <h3 style="margin: 20px 0 10px 0; font-weight: 700;">${t.planetaryPositions}</h3>
          <table>
            <thead>
              <tr>
                <th>${t.planet}</th>
                <th>${t.sign}</th>
                <th>${t.house}</th>
                <th>${t.degree}</th>
              </tr>
            </thead>
            <tbody>
              ${analysis.astrologyData.planets.map((p: any) => `
                <tr>
                  <td>${p.name || ''}</td>
                  <td>${p.sign || ''}</td>
                  <td>${t.house} ${p.house || ''}</td>
                  <td>${p.degree ? parseFloat(p.degree).toFixed(1) + '°' : ''}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        ` : ''}

        ${analysis.astrologyData.integratedCareerGuidance ? `
          <h3 style="margin: 20px 0 10px 0; font-weight: 700;">${t.integratedGuidance}</h3>
          <div class="list-item">
            ${analysis.astrologyData.integratedCareerGuidance}
          </div>
        ` : ''}
      ` : ''}

      <!-- 6-Month Pathway -->
      <div class="section-header">${t.sixMonthPlan}</div>
      ${analysis.sixMonthPathway.map(step => `
        <div class="pathway-box">
          <h3>${step.month}: ${step.title}</h3>
          <p style="margin: 10px 0;">${step.description}</p>
          <div style="margin-top: 15px;">
            <strong>${t.actions}:</strong>
            <ul>
              ${step.actions.slice(0, 3).map(action => `<li>${action}</li>`).join('')}
            </ul>
          </div>
          <div style="margin-top: 10px;">
            <strong>${t.milestones}:</strong>
            <ul>
              ${step.milestones.slice(0, 2).map(milestone => `<li>✓ ${milestone}</li>`).join('')}
            </ul>
          </div>
        </div>
      `).join('')}

      <!-- 3-Year Pathway -->
      <div class="section-header">${t.threeYearPlan}</div>
      ${analysis.threeYearPathway.map((step, index) => `
        <div class="pathway-box" style="background: #faf0ff; border-color: #800080;">
          <h3 style="color: #800080;">${t.year} ${index + 1}: ${step.title}</h3>
          <p style="margin: 10px 0;">${step.description}</p>
          <div style="margin-top: 15px;">
            <strong>${t.actions}:</strong>
            <ul>
              ${step.actions.slice(0, 3).map(action => `<li>${action}</li>`).join('')}
            </ul>
          </div>
          <div style="margin-top: 10px;">
            <strong>${t.milestones}:</strong>
            <ul>
              ${step.milestones.slice(0, 2).map(milestone => `<li>✓ ${milestone}</li>`).join('')}
            </ul>
          </div>
        </div>
      `).join('')}

      <!-- Conclusion -->
      <div class="section-header">${t.conclusion}</div>
      <div class="section">
        <p>${language === 'hi'
          ? `यह रिपोर्ट आपके करियर और जीवन की यात्रा के लिए एक व्यापक मार्गदर्शिका है। प्राचीन ज्ञान और आधुनिक विश्लेषण के संयोजन से, हमने आपकी अद्वितीय क्षमताओं और अवसरों की पहचान की है। याद रखें कि यह मार्गदर्शन है, न कि निर्धारित भाग्य। आपकी मेहनत, समर्पण और सही निर्णय आपकी सफलता के मुख्य कारक होंगे।`
          : `This report is a comprehensive guide for your career and life journey. Through the combination of ancient wisdom and modern analysis, we have identified your unique abilities and opportunities. Remember that this is guidance, not predetermined fate. Your hard work, dedication, and right decisions will be the main factors of your success.`
        }</p>
      </div>

      <!-- Disclaimer -->
      <div class="disclaimer-box">
        <h4>${t.disclaimer}</h4>
        <p>${t.disclaimerText}</p>
      </div>

      <div class="footer">
        ${t.footer}
      </div>
    </body>
    </html>
  `;
}

export const generatePDFReport = async (analysis: Analysis, language: 'en' | 'hi' = 'en', userName?: string) => {
  const htmlContent = createHTMLContent(analysis, language, userName);

  const container = document.createElement('div');
  container.innerHTML = htmlContent;
  container.style.position = 'absolute';
  container.style.left = '-9999px';
  container.style.top = '0';
  document.body.appendChild(container);

  // Wait for fonts to load
  if (language === 'hi') {
    await document.fonts.load('400 12px "Noto Sans Devanagari"');
    await document.fonts.load('700 12px "Noto Sans Devanagari"');
  }

  await new Promise(resolve => setTimeout(resolve, 500));

  try {
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
      width: 794,
      windowWidth: 794
    });

    const imgData = canvas.toDataURL('image/jpeg', 0.95);
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
      compress: true
    });

    const imgWidth = 210;
    const pageHeight = 297;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    let position = 0;

    pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight, undefined, 'FAST');
    heightLeft -= pageHeight;

    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight, undefined, 'FAST');
      heightLeft -= pageHeight;
    }

    const fileName = `Career_Blueprint_${language.toUpperCase()}_${new Date().getTime()}.pdf`;
    pdf.save(fileName);

    document.body.removeChild(container);
  } catch (error) {
    console.error('Error generating PDF:', error);
    document.body.removeChild(container);
    throw error;
  }
};
